# Static Site - No Build Config Needed
# [build]
#   publish = "."
#   command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

